# Generated by Django 4.2 on 2025-05-14 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('filial_id', models.IntegerField()),
                ('instructor_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('is_online', models.BooleanField(default=False)),
                ('filial_id', models.IntegerField()),
                ('instructor_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
