# Generated by Django 4.2 on 2025-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicelesson',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
