# Generated by Django 4.2 on 2025-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_practicelesson_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelesson',
            name='title',
            field=models.CharField(default='Practical lesson', max_length=100),
        ),
        migrations.AddField(
            model_name='theorylesson',
            name='title',
            field=models.CharField(default='Theoretical lesson', max_length=100),
        ),
    ]
