# Generated by Django 4.2 on 2025-06-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_practicelesson_title_theorylesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelesson',
            name='instructor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theorylesson',
            name='instructor_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
