# Generated by Django 4.2 on 2025-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_practicelesson_instructor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorylesson',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
