# Generated by Django 4.2 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drivingcategory_filial_group_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='filial',
        ),
        migrations.AddField(
            model_name='group',
            name='filial_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='driving_category',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='DrivingCategory',
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
