# Generated by Django 4.2 on 2025-05-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadVisualGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Road Visual Groups',
                'verbose_name_plural': 'Road Visual Groups',
            },
        ),
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rule Section',
                'verbose_name_plural': 'Rule Sections',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TrafficRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10, unique=True)),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pdr.rulesection')),
            ],
            options={
                'verbose_name': 'Traffic Rule',
                'verbose_name_plural': 'Traffic Rules',
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='RoadVisualElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('sign', 'Road Sign'), ('marking', 'Road Marking')], max_length=10)),
                ('element_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image_url', models.URLField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuals', to='pdr.roadvisualgroup')),
            ],
            options={
                'verbose_name': 'Road Visual Element',
                'verbose_name_plural': 'Road Visual Elements',
            },
        ),
    ]
