# Generated by Django 4.2 on 2025-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesection',
            name='number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
