# Generated by Django 4.2 on 2025-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdr', '0002_alter_rulesection_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadvisualelement',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='roadvisualgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='roadvisualgroup',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadvisualgroup',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='roadvisualgroup',
            name='type',
            field=models.CharField(choices=[('sign', 'Road Sign'), ('marking', 'Road Marking')], default='sign', max_length=10),
        ),
    ]
