# Generated by Django 4.2 on 2025-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdr', '0003_remove_roadvisualelement_element_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadvisualelement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='roadvisualelement',
            name='image',
            field=models.ImageField(default='signs-and-markings/default.png', upload_to='signs-and-markings/'),
        ),
    ]
