# Generated by Django 4.2 on 2025-05-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdr', '0004_remove_roadvisualelement_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficrule',
            options={'verbose_name': 'Traffic Rule', 'verbose_name_plural': 'Traffic Rules'},
        ),
    ]
