# Generated by Django 4.2 on 2025-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('liqpay_order_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=20)),
                ('liqpay_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('liqpay_payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('liqpay_sender_card_mask2', models.CharField(blank=True, max_length=20, null=True)),
                ('liqpay_sender_card_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('liqpay_sender_card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('liqpay_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
