# Generated by Django 4.2 on 2025-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_group_teacher_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('theory_practice', 'Theory and Practice')], max_length=20),
        ),
    ]
