# Generated by Django 4.2 on 2025-05-30 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice')], default='theory', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='user_profile.group'),
        ),
    ]
